### ISSUE TITLE
gomail: could not send email 1: StartTLS: x509: certificate is valid for HOSTNAME.DOMAIN, not xxx

### ISSUE THREAD

**Issue by joker-soft** [lejmr/iredmail-docker#13]
Create container no problem.However, Gogs failed to use SMTP (25 port ) to send letters.

execut bash:
echo $HOSTNAME > mail
echo $DOMAIN > jokersoft.io

error message:
gomail: could not send email 1: StartTLS: x509: certificate is valid for HOSTNAME.DOMAIN, not mail.jokersoft.io

No checksum found where hostname, Hope to be answered.

**Comment by lejmr** [comment]
Good call.. I would rather recommend using letsencrypt which you can mount to the container from host than using the initial self-signed certificate..  I am doing something like this:

```
volumes:
   - /etc/localtime:/etc/localtime:ro
   - /etc/letsencrypt/live/mail.lejmr.com/fullchain.pem:/etc/ssl/certs/iRedMail.crt:ro
   - /etc/letsencrypt/live/mail.lejmr.com/privkey.pem:/etc/ssl/private/iRedMail.key:ro
```
