### ISSUE TITLE
DKIM key only generated once for image

### ISSUE THREAD

**Issue by InfiniteLukeOne** [lejmr/iredmail-docker#17]
Hello,

I work on a fork of this repository, with some changes to the included components.
I realized that DKiM keys are only generated once by the installation of iRedMail, which means everyone using this docker image will have the same public/private key pair and could send emails with the domain of other users of this container and DKIM verification would pass. (Note: SPF would still fail)

Am I correct on this issue or did I miss something?

If someone confirms this issue, I could look into creating a script which saves (and uses) a freshly generated key-pair to the data directory outside of the container and include it in a pull request.

**Comment by TitanFighter** [comment]
@InfiniteLukeOne I also had this issue, but I do not use this repository because of two issues next to this one.

**Comment by twelsby** [comment]
I can confirm that this is indeed a problem.  This can be confirmed by creating a container, copying out the .key and .crt files, creating another container and repeating and then doing an MD5SUM on both sets of files, which will match.  There is no need to create a script however as iRedMail already includes a script to create the DKIM keys, it just needs to be run on first boot of the container.

**Comment by InfiniteLukeOne** [comment]
Thank you for your help on this issue.

Sadly iRedMail.key and iRedMail.crt aren't the relevant files for DKIM, but for SSL. The relevant private key for DKIM is in /var/lib/dkim/DOMAIN.pem (the file which is renamed in the amavis startup script) and the public key/dns record is in the iRedMail.tips file and in the initial email to the postmaster account.

I've found the relevant scripts here: https://docs.iredmail.org/sign.dkim.signature.for.new.domain.html

**Comment by InfiniteLukeOne** [comment]
I have the changes for the private key prepared, but I don't know how to replace the DNS record in iRedMail.tips and mail. I have to replace something like this:
```
; key#1 1024 bits, i=dkim, d=domain, /var/lib/dkim/DOMAIN.pem
dkim._domainkey.domain.    3600 TXT (
  "v=DKIM1; p="
  "MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC5qLy1jRYNVGxR+ZWieSMpcq5Z"
  "HOj3VPohXSM4IRIBTzYIyw8ffzg7sWJZeC7QsqMlm5MSYHeBpbYwEkCV5btvHjnT"
  "vxzCUI8PdNgZTdyMSgNsrqD0bSxidixTOHilbDzjdEC2WtzrbbvZp16r4AgTg3JF"
  "ave7kP2IKvqc+/zZLQIDAQAB")
```
with the new record (output of `amavisd-new showkeys`).

**Comment by twelsby** [comment]
After considering this a little more I am thinking that we can't simply generate a new DKIM record every time a container is created, as this would require updating the DNS record for the server.  It would be a pain to have to do this every time you create the container (or upgrade).  I guess a solution would be to put the pem file in a volume, which would then persist if the container is recreated.

**Comment by InfiniteLukeOne** [comment]
You are right. I almost forgot to put it outsider the container. The path to the pem file is configured in `mysql/services/amavis.sh` anyway, so we could change the path there. I will try this when I get home.

**Comment by twelsby** [comment]
The approach I think is best is to delete the .pem file generated by iRedMail.sh in the Dockerfile so that the image is created without one.  Then during the amavis.sh init script test for the existence of this file and if it doesn't exist create one.  Then leave it to the user to attach a volume at the appropriate mount point if they desire to retain their DKIM key between container generations.  I prefer this to declaring a volume at build time and ending up with an unnamed volume.

**Comment by twelsby** [comment]
DKIM generation now incorporated into pull request.  The tips and welcome email will be add to a separate pull request for lejmr/iredmail-docker#14.

**Comment by InfiniteLukeOne** [comment]
I believe this issue isn't fixed yet. Changes made in #18 to solve this issue were reverted with #36. Correct me if this issue was solved by other changes.

**Comment by lejmr** [comment]
Thank you for getting back to this issue. I actually manually merged that, as you can see here: https://github.com/lejmr/iredmail-docker/commit/edcd29ac73af8ba0fe926a153857cb6e7e1c8d03

You might notice I am didnt copied DKIM portions. I am just fixing it, and will make commit ASAP
