### ISSUE TITLE
Error messages during boot: unable to write 'random state'

### ISSUE THREAD

**Issue by twelsby** [lejmr/iredmail-docker#26]
During boot multiple instances of the message "unable to write 'random state'" appear after a message indicating rc.local is running.  This messages are caused by the fact that some environment variables normally set during boot are not set in the parent image, which means that openssl is unable to locate where to write its random file.  The simplest solution is to add the following line immediately before the openssl calls:

export RANDFILE=/root/.rnd

**Comment by hakula007** [comment]
@twelsby,
Could you please tell me which file need add below line, I use centos 7 run this docker image.
export RANDFILE=/root/.rnd

**Comment by hakula007** [comment]
@twelsby ，

When I run below command:
docker run --privileged -p 110:110 -p 443:443 -p 587:587 -p 143:143 -p 25:25 -p 993:993 -p 995:995 \
           -e "DOMAIN=example.com" -e "HOSTNAME=mail" \
           -e "MYSQL_ROOT_PASSWORD=password" \
           -e "SOGO_WORKERS=1" \
           -e "TIMEZONE=Europe/Prague" \
           -e "POSTMASTER_PASSWORD={PLAIN}password" \
           -e "IREDAPD_PLUGINS=['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']" \
           -v /var/www/iredmail/mysql:/var/lib/mysql \
           -v /var/www/iredmail/vmail:/var/vmail \
           -v /var/www/iredmail/clamav:/var/lib/clamav \
           --name=iredmail lejmr/iredmail:mysql-latest

got below error log, do you know what issue it is and how to fix it.
-----------------------------------------------------------------------------------------
May 28 11:27:19 c1a8371d329b root: DEBUG Starting amavisd-new
 * Starting app server(s) uwsgi
   ...done.
/usr/lib/python2.7/dist-packages/pymysql/cursors.py:158: Warning: '@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead
  result = self._query(query)
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 985 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 989 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 990 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 991 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 992 killed with signal 9
^[[18~^[[19~May 28 11:28:01 c1a8371d329b CRON[1303]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1275 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1276 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1277 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1278 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1279 killed with signal 9
