### ISSUE TITLE
ClamAV database should not be included in image

### ISSUE THREAD

**Issue by twelsby** [lejmr/iredmail-docker#28]
The current build process sees the iRedMail installation script download the ClamAV database, which are then stored in an archive file in /root.  Then on boot, if the clamav database files are missing (such as if a empty volume is being used) then this archive is extracted, and then the archive file is deleted.  Note that if an existing volume is used (that already has clamav database files) then the archive is not deleted.

It appears that the purpose of deleting the archive at runtime is to recover the disk space used, but docker images are immutable, so all that happens is that the writable layer of the container is modified to hide the file.  The file continues to exist in the image.  This means that we have two copies of the ClamAV database at all times, which amounts to an extra 164 MB or so.

The other problem that this approach creates is that the database used when a new clamav volume is initialized is current as of the build date.  Therefore it will be out of date until the next scheduled update. 
 Downloading the clamav database at build time also increases the build time.

The solution to these problems is to not download clamav during build time, but instead to download it at runtime, if necessary, instead of extracting the archive.  This gives us a faster build, a database that is as up to date as possible from the get go, and reduces the size of the image.

**Comment by lejmr** [comment]
Thank you for your contribution!
