### ISSUE TITLE
dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process

### ISSUE THREAD

**Issue by hakula007** [lejmr/iredmail-docker#37]
When I run below command:
docker run --privileged -p 110:110 -p 443:443 -p 587:587 -p 143:143 -p 25:25 -p 993:993 -p 995:995 \
           -e "DOMAIN=example.com" -e "HOSTNAME=mail" \
           -e "MYSQL_ROOT_PASSWORD=password" \
           -e "SOGO_WORKERS=1" \
           -e "TIMEZONE=Europe/Prague" \
           -e "POSTMASTER_PASSWORD={PLAIN}password" \
           -e "IREDAPD_PLUGINS=['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']" \
           -v /var/www/iredmail/mysql:/var/lib/mysql \
           -v /var/www/iredmail/vmail:/var/vmail \
           -v /var/www/iredmail/clamav:/var/lib/clamav \
           --name=iredmail lejmr/iredmail:mysql-latest

got below error log, anyone know what issue it is and how to fix it.
-----------------------------------------------------------------------------------------
May 28 11:27:19 c1a8371d329b root: DEBUG Starting amavisd-new
 * Starting app server(s) uwsgi
   ...done.
/usr/lib/python2.7/dist-packages/pymysql/cursors.py:158: Warning: '@@tx_isolation' is deprecated and will be removed in a future release. Please use '@@transaction_isolation' instead
  result = self._query(query)
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 985 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 989 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 990 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 991 killed with signal 9
May 28 11:27:48 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 992 killed with signal 9
^[[18~^[[19~May 28 11:28:01 c1a8371d329b CRON[1303]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: master: Error: service(lmtp): Initial status notification not received in 30 seconds, killing the process
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1275 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1276 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1277 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1278 killed with signal 9
May 28 11:28:18 c1a8371d329b dovecot: lmtp: Fatal: master: service(lmtp): child 1279 killed with signal 9

**Comment by lejmr** [comment]
Try the last version, as 0.9.8 has been released, and drop the variables DOMAIN and HOSTNAME in favour of -h argument.

**Comment by Ryu945** [comment]
I tried that using an NGINX and Let's Encrypt I found.  I still that get that same error.  He does use alot of ports in his setup?   Could the fact I only have 443 and 80 be causing this?

Here is my setup:

    image: lejmr/iredmail:mysql-latest
    container_name: iredmail-app
    hostname: apple.banana.com
    networks:
      - frutous
    depends_on:
      - letsencrypt
      - proxy
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/raid/iredmail/mysql:/var/lib/mysql
      - /mnt/raid/iredmail/vmail:/var/vmail
      - /mnt/raid/iredmail/clamav:/var/lib/clamav
    environment:
      - VIRTUAL_HOST=apple.banana.com
      - LETSENCRYPT_HOST=apple.banana.com
      - LETSENCRYPT_EMAIL=apple@bannana.com
      - MYSQL_ROOT_PASSWORD=password
      - POSTMASTER_PASSWORD={SSHA512}awellthoughtoutpassword
      - IREDAPD_PLUGINS="['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']"
      - SOGO_WORKERS=1
    restart: unless-stopped

I am using jwilder/nginx-proxy:alpine for NGINX and let's encrypt.


The error message for reference is:

iredmail-app   | Aug  7 14:36:01 inverseforestmail CRON[1752]: (sogo) CMD (/usr/sbin/sogo-tool expire-sessions 30 >/dev/null 2>&1; /usr/sbin/sogo-ealarms-notify >/dev/null 2>&1)


When I go to the page, it says there is a redirect problem.

**Comment by lejmr** [comment]
Please test version lejmr/iredmail:mysql-1.0-latest

**Comment by lejmr** [comment]
I am closing this ticket, as long as the master branch does not use phusion base image with this time of service starting mechanism.

If this problem prevails even for version 1.0, please open a new ticket. Since information inside of this ticket are not most likely related... thank you.
