### ISSUE TITLE
what pwd t ouse for /iredadmin?

### ISSUE THREAD

**Issue by erdalkaraca** [lejmr/iredmail-docker#38]
I have started the container as follows:

sudo docker run --privileged -p 10080:80 -p 10443:443 \
           -h mail.example.com \
		   -d \
           -e "MYSQL_ROOT_PASSWORD=mpwd" \
           -e "SOGO_WORKERS=1" \
           -e "TZ=Europe/Berlin" \
           -e "POSTMASTER_PASSWORD={PLAIN}ppwd" \
           -e "IREDAPD_PLUGINS=['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']" \
           -v /var/iredmail/mysql:/var/lib/mysql \
           -v /var/iredmail/vmail:/var/vmail \
           -v /var/iredmail/clamav:/var/lib/clamav \
           --name=iredmail lejmr/iredmail:mysql-latest

I am now trying to login into iredadmin but it keeps telling me the following acces data is invalid (I have anonymized the real domain/host name):

url: https://[host]:10443/iredadmin
user: postmaster@mail.example.com
pwd: ppwd

I tried both the IP of the host and mail.example.com

Error: Username or password is incorrect.

What do I miss?

**Comment by InfiniteLukeOne** [comment]
Have you tried postmaster@example.com yet?

**Comment by lejmr** [comment]
In your case, it is going to be postmaster@DOMAIN

Check the latest update. Ever since now, you need to start docker container specifying hostname,i.e, -h mail.example.com, and container will take care of rest..
