### ISSUE TITLE
Failed to build image

### ISSUE THREAD

**Issue by ysicing** [lejmr/iredmail-docker#41]
Hello, I found the following error while trying to build the image。
```
/bin/sh: 1: hostname_: not found
cat: /opt/hostname: No such file or directory
cat: /etc/mailname: No such file or directory
sed: -e expression #1, char 0: no previous regular expression
```

**Comment by ysicing** [comment]
Lower version docker is not supported

**Comment by BongoEADGC6** [comment]
@ysicing Which version did you use to cause the issue and update to to fix this?

**Comment by ysicing** [comment]
@BongoEADGC6  I switch the docker version to 18.06.0-ce and rebuild without error
