### ISSUE TITLE
docker exec iredmail 

### ISSUE THREAD

**Issue by malutanpetronel** [lejmr/iredmail-docker#42]
I am trying to connect to the machine docker exec iredmail bash but I get nothing more than a freezing command.
![image](https://user-images.githubusercontent.com/5830216/46223202-617fb600-c35b-11e8-82d6-1d223c0def5f.png)

**Comment by TitanFighter** [comment]
if `iresmail` is the name of container, then
`docker exec -it iresmail bash`

**Comment by malutanpetronel** [comment]
docker exec -it iredmail bash... and see then:
"I get nothing more than a freezing command."
as in the image

**Comment by malutanpetronel** [comment]
I was trying to exec in order to try to test the installation...

**Comment by lejmr** [comment]
what is the output of your docker ps command?
