### ISSUE TITLE
Is there anything required to migrate from 0.9.8 to 1.0?

### ISSUE THREAD

**Issue by TitanFighter** [lejmr/iredmail-docker#59]

**Comment by lejmr** [comment]
Actually, it is not that simple, but I didnt have much time though :-) Let me open a wiki page in here. I will put my notes on the upgrade. Generally, you need to 

1. wipe mysql directory
2. restore each database from backup
3. apply mysql migrations manually
4. restart container

Generally, rather simple, but you better have a backup. That was all.

**Comment by lejmr** [comment]
https://github.com/lejmr/iredmail-docker/wiki/Upgrade-from-0.9.8-to-1.0

**Comment by TitanFighter** [comment]
[Here](https://serverfault.com/questions/1014395/migration-iredmail-from-one-server-to-another-with-simultaneous-updating-from-0/1014396#1014396) I wrote a script which helps to migrate DB.

**Comment by kovalroma** [comment]
Hello, 
My installation is **iRedMail v0.9.7** with **MySQL v0.8**                                                             

I have a question according to the following steps:

1. wipe mysql directory
2. restore each database from backup
3. apply mysql migrations manually
4. restart container

> 1. wipe mysql directory and 2. restore each database from backup```

iRedMail creates backup of the following databases:
- amavasid
- iredadmin
- aredapd
- mysql
- rouncubemail
- sogo
- vmail

Do I really need to wipe mysql directory, or I can only wipe this databases (amavasid,iredadmin,aredapd,mysql,rouncubemail,sogo,vmail) and import from iRedaMail backup ?  

> 3. apply mysql migrations manually

Can you point me to the instruction ? 

Thank You in Advance

**Comment by TitanFighter** [comment]
> Can you point me to the instruction ?

Read one by one: https://docs.iredmail.org/iredmail.releases.html Also here you will find the answer for your the 1st and the 2nd questions (ie if DBs are not not changed in those instructions, you can simply restore them from your backups).
