### ISSUE TITLE
Unable to login to any service

### ISSUE THREAD

**Issue by agilob** [lejmr/iredmail-docker#6]
I started my docker instance with:

```
docker run --privileged -p 8666:80 -p 8443:443 \
           -e "DOMAIN=my.domain" -e "HOSTNAME=email" \
           -e "MYSQL_ROOT_PASSWORD=totallyMyPassword" \
           -e "SOGO_WORKERS=1" \
           -e "TIMEZONE=Europe/Warsaw" \
           -e "POSTMASTER_PASSWORD={PLAIN}asloMyPassword" \
           -e "IREDAPD_PLUGINS=['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']" \
           -v /mysql:/var/lib/mysql \
           -v /vmail:/var/vmail \
           -v /clamav:/var/lib/clamav \
           --name=iredmail lejmr/iredmail:mysql-latest
```

I'm unable to login to any service. I tried login with `postmaster@my.domain` or `postmaster@email.my.domain` or just `postmaster@email` (don't know where I found this) and the password provided in run command doesn't work. I tried also looking up iRedMail config (the one inside docker), it said password was `FUPASSWORD`, but it also didn't work. What would be the credentials to SOGo, iRedMail and Roundcube?

**Comment by lejmr** [comment]
In this case you should be able to use:

host: https://localhost:8443/iredadmin/
login: postmaster@my.domain
password: asloMyPassword

(worked for me when I started this command)

**Comment by lejmr** [comment]
In this case you should be able to use:

host: https://localhost:8443/iredadmin/
login: postmaster@my.domain
password: asloMyPassword

(worked for me when I started this command)

**Comment by agilob** [comment]
No, doesn't work for me, I just tried again with my actual password and domain and then with the ones provided in comment. None of them works.

**Comment by lejmr** [comment]
Please try lejmr/iredmail:mysql-0.9.7, and provide output of command (to see if everything finishes properly).

**Comment by agilob** [comment]
Well. this a bad idea. I run that command and I damaged my maria-db mysql because I didn't change default path to mysql databases... I just spent 1.5h recovering my base-system databases and files. For some reason -lastest didn't make any damage, but 0.9.7 did.

I think I know what's wrong with my setup - I have pre-existing entries in postmaster database from my hand-made email server, I'll confirm that later today.

**Comment by wireless-road** [comment]
Hello!
Got similar problem.
Here is how I start the container:
```
docker run --privileged -p 7080:80 -p 7443:443 \
           -h mydomain.com \
           -e "MYSQL_ROOT_PASSWORD=totallyMyPassword" \
           -e "SOGO_WORKERS=1" \
           -e "TZ=Europe/Moscow" \
           -e "POSTMASTER_PASSWORD={PLAIN}asloMyPassword" \
           -e "IREDAPD_PLUGINS=['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']" \
           -v /home/al/docker/iredmail/mysql:/var/lib/mysql \
           -v /home/al/docker/iredmail/vmail:/var/vmail \
           -v /home/al/docker/iredmail/clamav:/var/lib/clamav \
           --name=iredmail lejmr/iredmail:mysql-0.9.7
```
My nginx proxies mail.mydomain.com requests to localhost:7443 so I can open following page:
https://mail.mydomain.com/iredadmin/
But entering login as `postmaster@mydomain.com` and password `asloMyPassword` gives me `INVALID_CREDENTIALS` error.
Tried it with the latest and 0.9.7 versions without luck.
