### ISSUE TITLE
iRedMail.tips access & Docker Run Command

### ISSUE THREAD

**Issue by Darkknight33** [lejmr/iredmail-docker#62]
The Tips file contains a lot of useful information that is generated when iRedmail is installed. I accessed it by accessing the container shell and moving the file to another bound directory, but maybe the run command should have an extra bind mount for direct access to this? Also had to adjust PATH to /iredmail/ because that throws errors if you don't, and added -d. 

Here's the adjusted run command I used:

docker run -p 80:80 -p 443:443 -d \
           -h HOSTNAME.DOMAIN \
           -e "MYSQL_ROOT_PASSWORD=password" \
           -e "SOGO_WORKERS=1" \
           -e "TZ=Europe/Prague" \
           -e "POSTMASTER_PASSWORD={PLAIN}password" \
           -e "IREDAPD_PLUGINS=['reject_null_sender', 'reject_sender_login_mismatch', 'greylisting', 'throttle', 'amavisd_wblist', 'sql_alias_access_policy']" \
           -v /iredmail/mysql:/var/lib/mysql \
           -v /iredmail/vmail:/var/vmail \
           -v /iredmail/clamav:/var/lib/clamav \
           -v /iredmail:/opt/iredmail \
           --name=iredmail lejmr/iredmail:mysql-latest

**Comment by lejmr** [comment]
Thank you for feedback. 

What is the point of bind mount: _-v /iredmail:/opt/iredmail _ ? 

_-d_ is not present because that command is meant as a demo which should give you command line not to hide due to -d.. However, this is really a personal perspective. I believe everyone knows about -d parameter..

**Comment by Darkknight33** [comment]
/opt/iredmail contains an important iRedMail.tips generated file with credentials and information the user needs. FYI adding -v /iredmail:/opt/iredmail for some reason caused and error that would not allow it to start up correctly. I'm not certain why. Maybe /iredmail/iredmail:/opt/iredmail would work better.

If you read through some of the issues, it's clear a few people were struggling because for them PATH  was not an obvious a placeholder. Many people have all sorts of familiarity with running docker. For the most part, this command is only ever needed once. People may not take the time to learn to use docker well enough to know how the command options work and just be looking for instructions to getting the container running as quick as possible. I don't think there's much harm done in anticipating that and writing out the command appropriately for a basic copy/paste to function. Anyone who knows how the command works already doesn't need the placeholder and anyone who doesn't know won't be tripped up by not knowing any better.

**Comment by lejmr** [comment]
Will test the part with /opt/iredmail.

Second paragraph - fair enough! Will improve the README.md based on your feedback. I know some people were struggling with strange errors, but I never connected those problems with PATH.. Will improve the README.md then we can start measuring improvement :-)

**Comment by lejmr** [comment]
The bindmount of /opt/iredmail does not work, as described, so I only update PATH for all the previously stated bind mounts...
