### ISSUE TITLE
k8s

### ISSUE THREAD

**Issue by oubayun** [lejmr/iredmail-docker#65]
k8s pod not hostname,  but iredmail setting hostname, iredadmin for postmaster+hostname, not work hostname for k8s, login faild username "postmaster@"。

**Comment by lejmr** [comment]
k8s not yet supported so far.

**Comment by oubayun** [comment]
I have solved the problem of deploying to k8s, and now I want to see if I can package docker images with alpine.

**Comment by lejmr** [comment]
This container is based on standard installation mechanisms of iRedMail which is not prepared for Alpine, so I doubt if migration to Alpine is even possible. 

Feel free to get in touch with https://github.com/iredmail or https://twitter.com/iredmail, who is preparing Alpine based images. I believe his implementation will be a million times better than this container.
