### ISSUE TITLE
Could it be updated to v1.1?

### ISSUE THREAD

**Issue by TitanFighter** [lejmr/iredmail-docker#67]

**Comment by lejmr** [comment]
Already happened: https://hub.docker.com/r/lejmr/iredmail/tags?page=1&name=1.1

There is no schema change, so feel free to test that image version.

You are right, I totally forgot to merge this branch to master: https://github.com/lejmr/iredmail-docker/tree/1.1

Can you please validate the image and let me know. I would do the merge

**Comment by lejmr** [comment]
https://github.com/lejmr/iredmail-docker/pull/68
