### ISSUE TITLE
I use the latest docker file, but meet some mistakes 

### ISSUE THREAD

**Issue by Daopr** [lejmr/iredmail-docker#7]
unable to write 'random state'
unable to write 'random state'
unable to write 'random state'
unable to write 'random state'
unable to write 'random state'
unable to write 'random state'
unable to write 'random state'
*** Booting runit daemon...
*** Runit started as PID 15
*** Starting Memcached..
*** Configuring iredapd
Waiting for MySQL is up
..mysqld is alive

*** Configuring MySQL database.. (root password) (postmaster)
mysqldump: [Warning] Using a password on the command line interface can be insecure.
(postmaster password)
(service accounts)
done.
*** Starting MySQL database..
                *** Starting postfix..
*** Starting amavis..
*** Starting dovecot..
*** Starting sogo...
 * Starting app server(s) uwsgi
   ...done.

Limits: Global size limit set to 104857600 bytes.
Limits: File size limit set to 26214400 bytes.
Limits: Recursion level limit set to 16.
Limits: Files limit set to 10000.
Limits: MaxEmbeddedPE limit set to 10485760 bytes.
Limits: MaxHTMLNormalize limit set to 10485760 bytes.
Limits: MaxHTMLNoTags limit set to 2097152 bytes.
Limits: MaxScriptNormalize limit set to 5242880 bytes.
Limits: MaxZipTypeRcg limit set to 1048576 bytes.
Limits: MaxPartitions limit set to 50.
Limits: MaxIconsPE limit set to 100.
Limits: MaxRecHWP3 limit set to 16.
Limits: PCREMatchLimit limit set to 10000.
Limits: PCRERecMatchLimit limit set to 5000.
Limits: PCREMaxFileSize limit set to 26214400.
Archive support enabled.
Algorithmic detection enabled.
Portable Executable support enabled.
ELF support enabled.
Mail files support enabled.
OLE2 support enabled.
PDF support enabled.
SWF support enabled.
HTML support enabled.
XMLDOCS support enabled.
HWP3 support enabled.
Self checking every 3600 seconds.

looks fine,but when I open the link mail.xxx.com/mail, page shows : ERR_SSL_PROTOCOL_ERROR

**Comment by lejmr** [comment]
Can you please provide whole command which you used for starting? Thank you
