### ISSUE TITLE
Trouble setting up a mail client

### ISSUE THREAD

**Issue by AndreSouzaAbreu** [lejmr/iredmail-docker#87]
Hey buddy, can you give me a little help here?

I'm strugling with setting up a mail client for my iRedmail server. I tried to do so with neomut and thunderbird, but the mail clients are unable to log in. I don't think the problem is with the mail clients because I was able to use them for my gmail accounts. Did anyone was able to use iRedmail with a desktop mail client?

**Comment by TitanFighter** [comment]
Show your config for iredmail container and settings you use for desktop clients.

**Comment by AndreSouzaAbreu** [comment]
> Show your config for iredmail container and settings you use for desktop clients.

My iredmail container is [here on gitlab](https://gitlab.com/andresouzaabreu/docker-iredmail). For the desktop client, I tried with neomut and thunderbid. For thunderbid, it is just to follow the default steps on the GUI. On neomutt, it is a bit more complicated but if you want I can share the config. 

Actually, in the last couple of days I have been unable to receive and send email from my iRedmail (and I was able to do so before). There is something wrong on my server and that may be why I'm unable to set up a mail client. I'll see if I can fix the server, maybe I'll reinstall iRedmail again

**Comment by AndreSouzaAbreu** [comment]
> > Show your config for iredmail container and settings you use for desktop clients.
> 
> My iredmail container is [here on gitlab](https://gitlab.com/andresouzaabreu/docker-iredmail). For the desktop client, I tried with neomut and thunderbird. On thunderbird, it is just to follow the default steps on the GUI. On neomutt, it is a bit more complicated but if you want I can share the config.
> 
> Actually, in the last couple of days I have been unable to receive and send email from my iRedmail (and I was able to do so before). There is something wrong on my server and that may be why I'm unable to set up a mail client. I'll see if I can fix the server, maybe I'll reinstall iRedmail again

Yes, there wa a problem on the server. The error was "connect to 127.0.0.1[127.0.0.1]:10026: Connection refused". I restarted the mail server docker container and now I'm able to send and receive emails. The mail client should work now. I'll try it and reply here

**Comment by AndreSouzaAbreu** [comment]
@TitanFighter  I'm still being unable to set up a mail client wtith iredmail :(

**Comment by AndreSouzaAbreu** [comment]
Update: I was able to set up a mail client using Mozilla Thunderbird. WHen I set up a mail client Thunderbird ask me to confirm if I trust the mail server because it did not have a "secure sginature", that is, I didn't buy expensive SSL certificates. I use Let's Encrypt instead. However, I'm still unable to set up a mail client using mutt.... which I'll have to figure out
